      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          # Especifica la carpeta de salida que busca Vercel
          working-directory: ./build/web
          # Importante: para que Vercel no intente su propio build
          build-script: echo "Building is handled by previous step"
