name: Build and Deploy Flutter Web to Vercel v2

on:
  push:
    branches:
      - main # O la rama que uses (ej. master, develop)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0' # Versi√≥n compatible con tu paquete mobile_scanner

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        # Usa el comando sin especificar el renderer, dejando que Flutter lo decida por defecto (auto)
        run: flutter build web --release 

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          # Especifica la carpeta de salida que busca Vercel
          working-directory: ./build/web
          # Importante: para que Vercel no intente su propio build
          build-script: echo "Building is handled by previous step"
